name: content-web

on:
   push:
      branches:
         - main
      paths:
         - 'content-web/**'

   workflow_dispatch:

 env:
   imageRepository: 'content-web'
   resourceGroupName: 'fabmedical-MS'
   containerRegistryName: 'fabmedicalMS'
   containerRegistry: 'fabmedicalMS.azurecr.io'
   dockerfilePath: './content-web'
   tag: '${{ github.run_id  }}'

jobs:
   build-and-publish-docker-image:
     name: Build and Push Docker Image
     runs-on: ubuntu-latest
     steps:
     # Checkout the repo
     - uses: actions/checkout@main

     - name: Set up Docker Buildx
       uses: docker/setup-buildx-action@v1

     - name: Login to ACR
       uses: docker/login-action@v1
       with:
         registry: ${{ env.containerRegistry }}
         username: ${{ secrets.ACR_USERNAME }}
         password: ${{ secrets.ACR_PASSWORD }}

     - name: Build and push an image to container registry
       uses: docker/build-push-action@v2
       with:
         context: ${{ env.dockerfilePath  }}
         file: "${{ env.dockerfilePath }}/Dockerfile"
         pull: true
         push: true
         tags: |
           ${{ env.containerRegistry }}/${{ env.imageRepository }}:${{ env.tag }}
           ${{ env.containerRegistry }}/${{ env.imageRepository }}:latest
